// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

xdescribe('a test', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('firefox').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('a test', async function() {
    await driver.get("http://localhost:4200/")
    await driver.manage().window().setRect({ width: 550, height: 692 })
    await driver.findElement(By.id("ngb-nav-1")).click()
    await driver.findElement(By.css(".mb-3:nth-child(1) > .form-control")).click()
    await driver.findElement(By.xpath("//div[@id=\'ngb-nav-1-panel\']/app-heroes/div/app-form/div/input")).sendKeys("un heroe")
    await driver.findElement(By.name("description")).click()
    await driver.findElement(By.name("description")).sendKeys("una description")
    await driver.findElement(By.css(".btn")).click()
    {
      const element = await driver.findElement(By.css(".btn"))
    }
    {
      // const element = await driver.findElement(By.CSS_SELECTOR, "body")

    }
    await driver.findElement(By.css(".list-group-item:nth-child(4) > b")).click()
    // check that in this element the text is equal to "un heroe: una description"
    {
      const elements = await driver.findElements(By.css(".list-group-item:nth-child(4) > b"))
      assert(elements.length)
      assert.strictEqual(await elements[0].getText(), "un heroe:")
    }
  })
})
