// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('buttons', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('firefox').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  xit('buttons', async function() {
    await driver.get("http://localhost:4200/")
    await driver.manage().window().setRect({ width: 1191, height: 695 })
    await driver.findElement(By.id("ngb-nav-0")).click()
    await driver.findElement(By.css("tr:nth-child(1) > td:nth-child(1) > input")).click() // 1
    await driver.findElement(By.css("tr:nth-child(1) > td:nth-child(2) > input")).click() // 2
    await driver.findElement(By.css("tr:nth-child(1) > td:nth-child(3) > input")).click() // 3
    await driver.findElement(By.css("tr:nth-child(2) > td:nth-child(1) > input")).click() // 4
    await driver.findElement(By.css("tr:nth-child(2) > td:nth-child(2) > input")).click() // 5
    await driver.findElement(By.css("tr:nth-child(2) > td:nth-child(3) > input")).click() // 6
    await driver.findElement(By.css("tr:nth-child(3) > td:nth-child(1) > input")).click() // 7
    await driver.findElement(By.css("tr:nth-child(3) > td:nth-child(2) > input")).click() // 8
    await driver.findElement(By.css("tr:nth-child(3) > td:nth-child(3) > input")).click() // 9
    await driver.findElement(By.css("tr:nth-child(4) > td:nth-child(1) > input")).click() // 0
    await driver.findElement(By.css("tr:nth-child(1) > td:nth-child(4) > input")).click() // /
    await driver.findElement(By.css("tr:nth-child(2) > td:nth-child(4) > input")).click() // *
    await driver.findElement(By.css("tr:nth-child(3) > td:nth-child(4) > input")).click() // -
    await driver.findElement(By.css("tr:nth-child(4) > td:nth-child(4) > input")).click() // +
    await driver.findElement(By.css("tr:nth-child(4) > td:nth-child(3) > input")).click() // =
    await driver.findElement(By.css("tr:nth-child(4) > td:nth-child(2) > input")).click() // C
    await driver.findElement(By.id("result")).click()
  })

  // test 2+3=5
  it('buttons', async function() {
    await driver.get("http://localhost:4200/")
    await driver.manage().window().setRect({ width: 1191, height: 695 })
    await driver.findElement(By.id("ngb-nav-0")).click()
    await driver.findElement(By.css("tr:nth-child(1) > td:nth-child(2) > input")).click() // 2
    await driver.findElement(By.css("tr:nth-child(4) > td:nth-child(4) > input")).click() // +
    await driver.findElement(By.css("tr:nth-child(1) > td:nth-child(3) > input")).click() // 3
    await driver.findElement(By.css("tr:nth-child(4) > td:nth-child(3) > input")).click() // =
    {
      const element = await driver.findElement(By.id("result"))
      // get element value
      assert.strictEqual(await element.getAttribute('value'), '2+3=5')
    }
  })

  // test 2/0=Infinity
  it('buttons', async function() {
    await driver.get("http://localhost:4200/")
    await driver.manage().window().setRect({ width: 1191, height: 695 })
    await driver.findElement(By.id("ngb-nav-0")).click()
    await driver.findElement(By.css("tr:nth-child(1) > td:nth-child(2) > input")).click() // 2
    await driver.findElement(By.css("tr:nth-child(1) > td:nth-child(4) > input")).click() // /
    await driver.findElement(By.css("tr:nth-child(4) > td:nth-child(1) > input")).click() // 0
    await driver.findElement(By.css("tr:nth-child(4) > td:nth-child(3) > input")).click() // =
    {
      const element = await driver.findElement(By.id("result"))
      // get element value
      assert.strictEqual(await element.getAttribute('value'), '2/0=Infinity')
    }
  })

  // test test 1/10=0.1*3=0.3
  it('buttons', async function() {
    await driver.get("http://localhost:4200/")
    await driver.manage().window().setRect({ width: 1191, height: 695 })
    await driver.findElement(By.id("ngb-nav-0")).click()
    await driver.findElement(By.css("tr:nth-child(1) > td:nth-child(1) > input")).click() // 1
    await driver.findElement(By.css("tr:nth-child(1) > td:nth-child(4) > input")).click() // /
    await driver.findElement(By.css("tr:nth-child(1) > td:nth-child(1) > input")).click() // 1
    await driver.findElement(By.css("tr:nth-child(4) > td:nth-child(1) > input")).click() // 0
    await driver.findElement(By.css("tr:nth-child(4) > td:nth-child(3) > input")).click() // =
    await driver.findElement(By.css("tr:nth-child(2) > td:nth-child(4) > input")).click() // *
    await driver.findElement(By.css("tr:nth-child(1) > td:nth-child(3) > input")).click() // 3
    await driver.findElement(By.css("tr:nth-child(4) > td:nth-child(3) > input")).click() // =
    {
      const element = await driver.findElement(By.id("result"))
      // get element value
      assert.strictEqual(await element.getAttribute('value'), '0.1*3=0.3')
    }
  })
})
